// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal.ModelsBanco;

#nullable disable

namespace ProyectoFinal.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20231211015702_banco")]
    partial class banco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoFinal.ModelsBanco.Cuenta", b =>
                {
                    b.Property<string>("num_cuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cantidad_dinero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo_cuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("num_cuenta");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("ProyectoFinal.ModelsBanco.Transaccion", b =>
                {
                    b.Property<string>("id_movimientos")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("cantidad_enviada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nom_movimientos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("num_cuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id_movimientos");

                    b.HasIndex("num_cuenta");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("ProyectoFinal.ModelsBanco.UsuarioBanco", b =>
                {
                    b.Property<string>("Cedula_usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("num_cuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pri_apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seg_apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula_usuario");

                    b.HasIndex("num_cuenta")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoFinal.ModelsBanco.Transaccion", b =>
                {
                    b.HasOne("ProyectoFinal.ModelsBanco.Cuenta", "Cuenta")
                        .WithMany("Transaccions")
                        .HasForeignKey("num_cuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("ProyectoFinal.ModelsBanco.UsuarioBanco", b =>
                {
                    b.HasOne("ProyectoFinal.ModelsBanco.Cuenta", "Cuenta")
                        .WithOne("UsuarioBanco")
                        .HasForeignKey("ProyectoFinal.ModelsBanco.UsuarioBanco", "num_cuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("ProyectoFinal.ModelsBanco.Cuenta", b =>
                {
                    b.Navigation("Transaccions");

                    b.Navigation("UsuarioBanco");
                });
#pragma warning restore 612, 618
        }
    }
}
